# Generated by Django 2.2.3 on 2019-07-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pyapp',
            new_name='voting',
        ),
    ]
