# Generated by Django 2.2.3 on 2019-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20190722_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rolno', models.CharField(max_length=150)),
                ('UserName', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='voting',
        ),
    ]
