# Generated by Django 2.2.3 on 2019-07-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20190722_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='UserName',
            new_name='Username',
        ),
    ]
