# Generated by Django 2.2.3 on 2019-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.ImageField(max_length=225, null=True, upload_to='symbols/'),
        ),
    ]
